# Generated by Django 5.1.1 on 2024-09-07 07:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255, verbose_name='Название книги')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('book_description_ru', models.TextField(blank=True, null=True, verbose_name='Описание книги (рус)')),
                ('book_description_kz', models.TextField(blank=True, null=True, verbose_name='Описание книги (каз)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('book_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус книги')),
                ('book_language', models.CharField(blank=True, max_length=100, null=True, verbose_name='Язык книги')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID клуба')),
                ('user_id', models.JSONField(verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Телефонный номер')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хэш пароля')),
                ('stage', models.CharField(max_length=50, verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.club', verbose_name='Клуб')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Член клуба',
                'verbose_name_plural': 'Члены клуба',
            },
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255, verbose_name='Подпись')),
                ('image_id', models.CharField(max_length=255, verbose_name='ID изображения')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Создание',
                'verbose_name_plural': 'Создания',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='adminpanel.book', verbose_name='Книга')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='adminpanel.comment', verbose_name='Родительский комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка пользователя')),
                ('user_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')),
                ('user_read_status', models.CharField(max_length=50, verbose_name='Статус чтения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Книжная полка',
                'verbose_name_plural': 'Книжные полки',
            },
        ),
    ]
