import { Book } from './bookTypes';

export const initialBooks: Book[] = [
  {
    id: 1,
    img: "https://avatars.dzeninfra.ru/get-zen_doc/1129675/pub_607bd4d719675453a503744e_607bd8a9efdbbb14a268d600/scale_1200",
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    genre: 'Self-help',
    year: 2016,
    rating: 4,
    description: 'A counterintuitive approach to living a good life, this book challenges readers to embrace negative experiences.',
    bookmarked: false,
  },
  {
    id: 2,
    img: "https://imo10.labirint.ru/books/442671/cover.jpg/242-0",
    title: 'Me Before You',
    author: 'Jojo Moyes',
    genre: 'Romance',
    year: 2012,
    rating: 4,
    description: 'A heartwarming tale of love and loss that will make you laugh, cry, and think.',
    bookmarked: false,
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
    title: '1984',
    author: 'George Orwell',
    genre: 'Dystopian',
    year: 1949,
    rating: 5,
    description: 'A chilling portrayal of a totalitarian future where critical thought is suppressed.',
    bookmarked: false,
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/71FxgtFKcQL._AC_UF1000,1000_QL80_.jpg",
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Classic',
    year: 1960,
    rating: 5,
    description: 'A powerful exploration of racial injustice and loss of innocence in the American South.',
    bookmarked: false,
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/71FxgtFKcQL._AC_UF1000,1000_QL80_.jpg",
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Classic',
    year: 1960,
    rating: 5,
    description: 'A powerful exploration of racial injustice and loss of innocence in the American South.',
    bookmarked: false,
  },
];
